fixtures:
  repositories:
    stdlib:        'https://github.com/puppetlabs/puppetlabs-stdlib.git'
    systemd:       'https://github.com/camptocamp/puppet-systemd'
    concat:        'https://github.com/puppetlabs/puppetlabs-concat'
    vcsrepo:       'https://github.com/puppetlabs/puppetlabs-vcsrepo.git'
    apt:           'https://github.com/puppetlabs/puppetlabs-apt.git'
  symlinks:
    base: "#{source_dir}"
