---
rvm:
  - 2.1.9
  - 2.2.6
  - 2.3.0
  - 2.4.1
env:
  matrix:
    - PUPPET_VERSION=4.9
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
    - rvm: 2.4.1
      env: PUPPET_VERSION=5.0
    # Acceptance tests
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-6
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/centos-7
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-14.04
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
    - rvm: 2.3.1
      dist: trusty
      env: PUPPET_INSTALL_TYPE=agent BEAKER_debug=true BEAKER_set=docker/ubuntu-16.04
      script: bundle exec rake beaker
      services: docker
      bundler_args: --without development
bundler_args: --without system_tests development
sudo: false
